### ISSUE TITLE
Asynchronous API calls

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/azure-operator#171]
### Current state
azure-operator currently sits waits for every asynchronous request made to Azure API. This time could used to perform other operations and to improve efficiency towards handling large amount of guest clusters.
e.g. If two successive operation for creation and deletion of the same guest cluster are made. The delete operation would have to wait until the create command has completed, which is usually between 5 and 10 minutes on azure.

### Issue
We ran into an issue where e2e tests failed because azure-operator did not provided any output during 10 minutes, while it was operating a delete cluster operation.
see: https://github.com/giantswarm/azure-operator/pull/162#issuecomment-380468647

## Proposal
Let asynchronous azure API request operate asynchronously.
On each resync period we can read the current operation's [provision state](https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2018-01-01/network/models.go#L974-L986) and proceed with adequate reconciliation operation.

## Implementation
* Provide resource's `ProvisioningState` in `CurrentState` and `DesiredState`
* Take `ProvisioningState` during reconciliation
* Do not wait and return an error during asynchronous operation. So we do not reconcile next resource, and next resync period will check for the current state of the current resource.

**Comment by kopiczko** [comment]
Ping @giantswarm/sig-operator

**Comment by xh3b4sd** [comment]
I mentioned already that we do this in the aws-operator so you can check the code there for inspiration and guiding. The [current state](https://github.com/giantswarm/aws-operator/blob/461f41f31acb021f93270df443c9865894c44eea/service/awsconfig/v10/resource/cloudformation/current.go#L32) uses a service implementation for the state magic. The stack state in this case is added to [the dispatched state object](https://github.com/giantswarm/aws-operator/blob/461f41f31acb021f93270df443c9865894c44eea/service/awsconfig/v10/resource/cloudformation/current.go#L128) so it is available in all resource steps. [The stack creation](https://github.com/giantswarm/aws-operator/blob/461f41f31acb021f93270df443c9865894c44eea/service/awsconfig/v10/resource/cloudformation/create.go#L25-L51) blocks because of the CF primitives so we just have a check for the state and break up after a couple of seconds if we do not see what we want and need. Then the reconciliation of the resource is canceled so other resources can go ahead and the framework can faster go on to the next CR. For [deletion](https://github.com/giantswarm/aws-operator/blob/461f41f31acb021f93270df443c9865894c44eea/service/awsconfig/v10/resource/cloudformation/delete.go#L24) we have the state check and stop reconciliation by returning an error to make the deletion happen again. This works because we use finalizers. To make this work for the azure-operator we need to use the latest operatorkit version in the vendor deps. Hope that helps. This looks like a lot but it is actually not that much and quite straight forward.

**Comment by kopiczko** [comment]
During https://github.com/giantswarm/giantswarm/issues/2483 I realized we need that to finish the story. Redeploying templates for single guest clusters takes like 1-2min. Resync period is 5min. So we can reconcile at best 4 clusters in the resync period.

**Comment by JosephSalisbury** [comment]
This has been done too.
