### ISSUE TITLE
Improve deployments collector

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/azure-operator#740]
# Current status

Currently our operator loops though all tenant clusters and collects metrics for all deployments in the resource group for every tenant cluster.

Then, for each deployment it exposes 4 metrics: one for each potential deployment status https://github.com/giantswarm/azure-operator/blob/6c36134e06aa21f0f5b5146019f59fa6bc03fb2a/service/collector/deployment.go#L119-L152

This gets use something like this

![image](https://user-images.githubusercontent.com/627038/77938064-7bce8300-72b5-11ea-868e-691eb17b1b8a.png)

We then have an alert that will page if there is a metric containing the label `Failed` and the value 1 https://github.com/giantswarm/g8s-prometheus/blob/e6dfbef20e33c844b77d16866efe48e4b79e5cc3/helm/g8s-prometheus-chart/prometheus-rules/azure.rules.yml#L4-L17

# Improvements

## Expose only interesting deployment's statuses

I'm not sure there is value in exposing the succeeded deployments in a resource group. I was thinking that maybe it makes more sense to expose only the statuses that are interesting, like failed deployments. Or running deployments, if we want to send an alert when a deployment has been running for long time. Anyway, what I mean is that maybe is not useful to collect all potential statuses for a deployment when we only care about 1 or 2.

## Number of deployments

Customers don't create resources inside our resource groups, right? If that's the case, we can collect a metric with the number of deployments in the tenant cluster resource gruop. If it doesn't match the expected deployment count, it should page.

**Comment by nprokopic** [comment]
> I'm not sure there is value in exposing the succeeded deployments in a resource group.

I see your point, it's a desired outcome and most of the deployments succeed in most of the cases. We could live without tapping ourselves on the back when we succeesfully deploy :smile:

Exposing successful deployments could though be useful, if, for example, we want to have metrics about deployments success rate maybe, that could make sense when we have more installations in more regions, so we could have some % data per customer/installation/region/etc to compare. Seeing that some resource deployments success rate dropped `X`% only in some Azure region or installation could be helpful.

> I was thinking that maybe it makes more sense to expose only the statuses that are interesting, like failed deployments. Or running deployments, if we want to send an alert **when a deployment has been running for long time**.

- Would having only `Running` and `Failed` statuses exposed be enough then? Since a deployment is done when it changes status from `Running` to `Succeeded` in this case.
- How would we know what happened without seeing a change from `Running` to `Succeeded` or `Failed`? Maybe reporting when it goes into `Failed` state, and not caring otherwise?
